apiVersion: v1
kind: Namespace
metadata:
  name: andy-iis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andy-iis
  namespace: andy-iis
  labels:
    app: andy-iis
spec:
  replicas: 1
  template:
    metadata:
      name: andy-iis
      namespace: andy-iis
      labels:
        app: andy-iis
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: andy-iis
        # image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        image: monopot/iis:core-log-relay-1.0.1
        # resources:
        #   limits:
        #     cpu: 1
        #     memory: 800M
        #   requests:
        #     cpu: .1
        #     memory: 300M
        ports:
          - containerPort: 80
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          value: spot
          operator: Equal
  selector:
    matchLabels:
      app: andy-iis
---
apiVersion: v1
kind: Service
metadata:
  name: andy-iis
  namespace: andy-iis
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: andy-iis