apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: iis-log-relay
  namespace: iis-log-relay
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       iis-log-relay
  updatePolicy:
    updateMode: "Off"